//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssessmentSystem.MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonLogin
    {
        public int PersonLoginId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int PersonId { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
